"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
const products=[
{no:"01",type:"FLOOR CARE",name:"Pine & Lemongrass",copy:"Refreshing pine and lemongrass freshness for an inviting everyday clean.",tone:"green",image:"https://assets.zyrosite.com/cdn-cgi/image/format%3Dauto%2Cw%3D375%2Ch%3D375%2Cfit%3Dcrop/mP43Lywkj9f4Rjq9/whatsapp-image-2025-09-06-at-23.47.30-2-Yle4ND3x1jcpVM0V.webp"},
{no:"02",type:"FLOOR CARE",name:"White Floor Cleaner",copy:"Everyday floor care with a fresh pine character and clean finish.",tone:"cream",image:"https://assets.zyrosite.com/cdn-cgi/image/format%3Dauto%2Cw%3D375%2Ch%3D375%2Cfit%3Dcrop/mP43Lywkj9f4Rjq9/white-phenyl-YD0EjllLeEsWRqKW.jpeg"},
{no:"03",type:"BATHROOM CARE",name:"Toilet Cleaner",copy:"Purpose-built bathroom cleaning for tough stains and a visibly clean finish.",tone:"mint",image:"https://assets.zyrosite.com/cdn-cgi/image/format%3Dauto%2Cw%3D375%2Ch%3D375%2Cfit%3Dcrop/mP43Lywkj9f4Rjq9/whatsapp-image-2025-09-07-at-10.45.53-YZ9ENWOO30sWVjz7.webp"}
];
const pineImage="https://assets.zyrosite.com/cdn-cgi/image/format%3Dauto%2Cw%3D375%2Ch%3D375%2Cfit%3Dcrop/mP43Lywkj9f4Rjq9/whatsapp-image-2025-09-06-at-23.47.30-2-Yle4ND3x1jcpVM0V.webp";
const toiletImage="https://assets.zyrosite.com/cdn-cgi/image/format%3Dauto%2Cw%3D375%2Ch%3D375%2Cfit%3Dcrop/mP43Lywkj9f4Rjq9/whatsapp-image-2025-09-07-at-10.45.53-YZ9ENWOO30sWVjz7.webp";
export default function Home(){const[open,setOpen]=useState(false),[progress,setProgress]=useState(0),[scrollY,setScrollY]=useState(0);useEffect(()=>{const f=()=>{const y=window.scrollY,m=document.documentElement.scrollHeight-innerHeight;setScrollY(y);setProgress(m?(y/m)*100:0)};addEventListener("scroll",f,{passive:true});f();return()=>removeEventListener("scroll",f)},[]);const journeyX=Math.sin(scrollY/520)*38,journeyY=Math.min(scrollY*.18,420),journeyRotate=scrollY*.16;return <><div className="progress" style={{width:`${progress}%`}}/><div className="journey-bottle" style={{position:"fixed",width:"clamp(105px,13vw,160px)",height:"clamp(200px,28vw,300px)",right:"7vw",top:"12vh",zIndex:20,pointerEvents:"none",transform:`translate3d(${journeyX}px,${journeyY}px,0) rotate(${journeyRotate}deg)`,opacity:scrollY<500?0:Math.max(.12,1-(scrollY-2600)/900)}}><img src={pineImage} alt="Mr Glowra Pine and Lemongrass Floor Cleaner"/></div><header className="nav"><Link href="#home" className="logo"><span>MG</span><b>MR GLOWRA</b></Link><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Menu">☰</button><nav className={open?"nav-links open":"nav-links"}><Link href="#products">Products</Link><Link href="/blog">Glowra Insights</Link><Link href="#story">Our Story</Link><Link href="#lucky">Lucky Draw</Link><Link href="#distributor">Distributors</Link><Link className="nav-pill" href="#contact">Contact</Link></nav></header><main>
<section id="home" className="hero"><div className="hero-noise"/><div className="hero-copy show"><div className="eyebrow">MADE IN UTTARAKHAND <i/> PREMIUM HOME CARE</div><h1>Power that <em>shines.</em><br/>Freshness that lasts.</h1><p>Premium floor and toilet care created for modern homes that expect a beautiful finish, effective everyday cleaning and freshness they can feel.</p><div className="actions"><a className="button primary" href="#products">Explore products →</a><Link className="button outline" href="/blog">Glowra Insights</Link></div><div className="hero-meta"><span>✦ Everyday floor care</span><span>✦ Fresh pine character</span></div></div><div className="hero-product show"><div className="sun"/><div className="real-hero-bottle"><img src={pineImage} alt="Mr Glowra Pine and Lemongrass Floor Cleaner"/></div><div className="real-hero-bottle secondary"><img src={toiletImage} alt="Mr Glowra Toilet Cleaner"/></div><div className="round-badge">✦<b>PURE<br/>FRESHNESS</b></div></div><a className="scroll" href="#story">SCROLL ↓</a></section>
<section id="story" className="statement section"><div className="kicker">THE GLOWRA IDEA</div><div className="statement-grid"><h2>Clean should feel<br/><em>good.</em></h2><div><p>Mr Glowra brings thoughtful formulas, fresh fragrance and premium presentation together — because the products you use every day deserve to feel special.</p><a className="under-link" href="#products">Meet the collection →</a></div></div></section>
<section id="products" className="products section"><div className="heading-row"><div><div className="kicker">THE COLLECTION</div><h2>Choose your <em>clean.</em></h2></div><p>Three essentials. One simple promise: make everyday cleaning better.</p></div><div className="cards">{products.map(p=><article className={`product-card ${p.tone}`} key={p.no}><div className="card-no">{p.no}</div><div className="product-visual"><img className="real-product-photo" src={p.image} alt={`Mr Glowra ${p.name}`} loading="lazy"/></div><div className="product-copy"><span>{p.type}</span><h3>{p.name}</h3><p>{p.copy}</p><a href="#contact">Product details →</a></div></article>)}</div></section>
<section id="why" className="dark-section"><div className="dark-image"><div className="image-shade"/><div className="image-tag">PINE <b>×</b> LEMONGRASS</div></div><div className="dark-copy"><div className="kicker light">NATURE MEETS PERFORMANCE</div><h2>A little forest<br/>in every <em>clean.</em></h2><p>Pine gives the collection its deep, clean character. Lemongrass brings a bright, uplifting note. Together, they turn a routine floor clean into a fresher home ritual.</p><div className="feature-list"><div><b>01</b><span>Fresh<br/>fragrance</span></div><div><b>02</b><span>Everyday<br/>floor care</span></div><div><b>03</b><span>Made in<br/>Uttarakhand</span></div></div></div></section>
<section className="values section"><div className="kicker">WHY MR GLOWRA</div><h2>Small details.<br/><em>Big difference.</em></h2><div className="value-grid"><div><span>01</span><h3>Premium feel</h3><p>Modern design and a considered product experience from bottle to finish.</p></div><div><span>02</span><h3>Fresh character</h3><p>Pine and lemongrass notes designed to leave your space feeling refreshed.</p></div><div><span>03</span><h3>Made locally</h3><p>Proudly built in Uttarakhand with an ambition to reach homes across India.</p></div></div></section>
<section id="lucky" className="lucky"><div className="lucky-art">✦<strong>GLOWRA</strong><small>LUCKY DRAW</small></div><div><div className="kicker">A LITTLE EXTRA GLOW</div><h2>Buy. Review.<br/><em>Win a year of Glowra.</em></h2><p>Eligible Flipkart customers who submit a genuine product review can participate in the periodic Mr Glowra Lucky Draw. Winners receive one bottle per month for one year, subject to the official terms.</p><Link className="button dark-button" href="/lucky-draw">View Lucky Draw Rules →</Link></div></section>
<section id="distributor" className="distributor"><div className="rings"/><div className="kicker">GROW WITH MR GLOWRA</div><h2>Bring the power of <em>Glowra</em><br/>to your market.</h2><p>Partner with a growing home-care brand and bring premium everyday cleaning to more customers.</p><a className="button dark-button" href="#contact">Apply for distributorship →</a></section>
<section className="insights section"><div className="heading-row"><div><div className="kicker">GLOWRA INSIGHTS</div><h2>Useful ideas for a<br/><em>cleaner life.</em></h2></div><Link className="outline-link" href="/blog">View all articles →</Link></div><div className="article-grid"><Article title="Why Toilet and Floor Hygiene Matter More Than You Think" text="A practical guide to household hygiene in Indian homes."/><Article title="Best Floor Cleaner in India: Expert Review" text="What actually matters when choosing a floor cleaner."/><Article title="Best Toilet Cleaner for Toilet Bowl" text="Stains, limescale, cleaning methods and product guidance."/></div></section>
<section className="contact section" id="contact"><div><div className="kicker">LET'S CONNECT</div><h2>Ready to make<br/>cleaning <em>shine?</em></h2></div><div className="contact-box"><p>For product enquiries, distribution and partnerships.</p><a href="mailto:contact@mrglowra.com">contact@mrglowra.com</a><Link href="/shop">Explore the shop →</Link></div></section></main></>}
function Article({title,text}){return <article className="article"><div className="article-image"/><span className="category">GLOWRA INSIGHTS</span><h3>{title}</h3><p>{text}</p><Link href="/blog">Read article →</Link></article>}
